const list = [
    {
        id: 1,
        title: "Beer Pilsner",
        price: 3.5,
        img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 2,
        title: "Beer Helles",
        author: "by Maple Press  | 1 September 2020",
        price: 3.8,
        img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 3,
        title: "Black Beer",
        author: "by Om Books Editorial Team  | 25 November 2018",
        price: 4.2,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 4,
        title: "Vodka",
        author: "by Wonder House Books | 25 April 2018",
        price: 5.5,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 5,
        title: "Gin",
        author: "by Wonder House Books  | 1 January 2018",
        price: 5.5,
        img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 6,
        title: "White Rum",
        author: "by Om Books Editorial Team | 30 September 2020",
        price: 6,
        img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 7,
        title: "Dark Rum",
        author: "by Om Books Editorial Team  | 1 January 2021",
        price: 7,
        img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 8,
        title: "Margarita",
        author: "by Wonder House Books  | 6 December 2020",
        price: 8,
        img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 9,
        title: "Negroni ",
        author: "by Content Team at Target Publications",
        price: 8.5,
        img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 11,
        title: "Gin Basil Smash",
        author: "by Maple Press | 1 September 2021",
        price: 11,
        img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 11,
        title: "Esspreso Martini",
        author: "by Rebecca Smith  | 14 December 2021",
        price: 9.5,
        img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 12,
        title: "Zombie",
        author: "by Sudha Murty | 1 January 2015",
        price: 10,
        img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
];

export default list;
