import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function HomeScreen() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home</h1>
        <button>
          <Link href="/">Go back</Link>
        </button>
      </main>
    </>
  );
}
