const data = {
    products: [
        {
            id: 1,
            name: "Beer Pilsner",
            price: 3.5,
            image: "./images_drinks/clear_pilsner.png",
            category: "beers",
        },
        {
            id: 2,
            name: "Beer Helles",
            price: 3.8,
            image: "./images_drinks/beer_helles.png",
            category: "beers",
        },
        {
            id: 3,
            name: "Black Beer",
            price: 4.2,
            image: "./images_drinks/black_beer.png",
            category: "beers",
        },
        {
            id: 4,
            name: "Vodka",
            price: 5.5,
            image: "./images_drinks/vodka.png",
            category: "cocktails",
        },
        {
            id: 5,
            name: "Gin",
            price: 5.5,
            image: "./images_drinks/gintonic.png",
            category: "cocktails",
        },
        {
            id: 6,
            name: "Dark Rum",
            price: 6.5,
            image: "./images_drinks/dark_rum.png",
            category: "cocktails",
        },
        {
            id: 7,
            name: "Dry Martini",
            price: 8,
            image: "./images_drinks/dry_martini.png",
            amount: 1,
            category: "cocktails",
        },
        {
            id: 8,
            name: "Margarita",
            price: 8.5,
            image: "./images_drinks/margarita.png",
            amount: 1,
            category: "cocktails",
        },
        {
            id: 9,
            name: "Negroni ",
            price: 8.5,
            image: "./images_drinks/negroni.png",
            category: "cocktails",
        },
        {
            id: 10,
            name: "Gin Basil Smash",
            price: 12,
            image: "./images_drinks/ginbasil.png",
            category: "cocktails",
        },
        {
            id: 11,
            name: "Espresso Martini",
            price: 9.5,
            image: "./images_drinks/espresso_martini1.png",
            category: "cocktails",
        },
        {
            id: 12,
            name: "Zombie",
            price: 10,
            image: "./images_drinks/zombie.png",
            category: "cocktails",
        },
        {
            id: 13,
            name: "Krombacher",
            price: 3.8,
            image: "./images_drinks/krombacher.png",
            category: "beers",
        },
        {
            id: 14,
            name: "Chardonay",
            price: 7.5,
            image: "./images_drinks/whitewine.png",
            category: "wines",
        },
        {
            id: 15,
            name: "Cabernet",
            price: 8.5,
            image: "./images_drinks/redwine.png",
            category: "wines",
        },
        {
            id: 16,
            name: "Merlot",
            price: 8,
            image: "./images_drinks/redwine.png",
            category: "wines",
        },
    ],
};

export default data;